//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeicoData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDB
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string UserName { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Message { get; set; }
        public string Comment { get; set; }
    }
}
