//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeicoData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public Nullable<int> typeno { get; set; }
        public string USERNAME { get; set; }
        public string pass { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> insert { get; set; }
        public Nullable<System.DateTime> update { get; set; }
        public int Id { get; set; }
    }
}
